import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '@/components/navigation/Navbar'
import HomepageHero from '@/components/homepage/HomepageHero'

import {
  Box,

} from '@chakra-ui/react'


const Home: NextPage = () => {
  
  
  
  return (
    <Box>
      <Head>
        <title>Magnetic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomepageHero />
      
     
    </Box>



  )
}

export default Home